Repository pantos-io/client-library, pull requests merged in 2024-07, with the labels that each got.

#19 [PAN-1998] Upgrade to hexbytes 1.x and versioned contract ABIs
  pantos/client/library/blockchains/base.py
  pantos/client/library/blockchains/ethereum.py
  poetry.lock
  pyproject.toml
Labels: dependencies

#20 [PAN-1989] return service node address of token transfers and update commo…
  README.md
  client-library.yml
  example.py
  pantos-client-library.conf
  pantos/client/library/api.py
  pantos/client/library/business/transfers.py
  poetry.lock
Labels: enhancement

#21 [PAN-1990] Read transfer data from destination blockchain
  client-library.yml
  pantos/client/library/blockchains/base.py
  pantos/client/library/blockchains/ethereum.py
  pantos/client/library/blockchains/solana.py
  pantos/client/library/configuration.py
  tests/blockchains/test_ethereum.py
  tests/conftest.py
Labels: enhancement

#24 [PAN-1992] API and example for getting a token transfer status
  README.md
  pantos/client/library/api.py
  pantos/client/library/entitites.py
  poetry.lock
  pyproject.toml
  tests/test_api.py
Labels: enhancement

#26 [PAN-1966] export token transfer status to API
  pantos/client/library/api.py
  tests/conftest.py
Labels: enhancement

#33 fix: update version to 1.1.4
  poetry.lock
  pyproject.toml
Labels: documentation
